"use client";

import Navigation from "../components/navigation";

// export const metadata = {
//   title: "Home | Next Movies",
//   description: "Generated by Next.js",
// };

export default function LayoutAboutUs({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
